# Generated by Django 3.2.2 on 2021-07-14 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=100)),
                ('time_create', models.DateTimeField(default=datetime.datetime(2021, 7, 15, 0, 19, 16, 73718))),
            ],
        ),
    ]
